config/routes.rb
Rails.application.routes.draw do

  resources :surveys
  root to: 'surveys#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  # attr_accessible :content, :question_id
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  # attr_accessible :content, :survey_id
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  # attr_accessible :name
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.create(survey_params)
    if @survey.valid?
      redirect_to @survey, notice: "Successfully created survey."
    else
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(survey_params)
      redirect_to @survey, notice: "Successfully updated survey."
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url, notice: "Successfully destroyed survey."
  end

  def survey_params
    params.require(:survey).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questionnaire</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
  <% if @survey.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :questions do |builder| %>
  <%= render 'question_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :questions %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render "form" %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% @surveys.each do |survey| %>
  <div class="article">
    <h2><%= link_to survey.name, survey %></h2>
    <%= pluralize(survey.questions.size, "Question") %>
  </div>
<% end %>

<p><%= link_to 'New Survey', new_survey_path %></p>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "form" %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>

<ol class="questions">
<% @survey.questions.each do |question| %>
  <li>
    <%= question.content %>
    <ol class="answers">
      <% question.answers.each do |answer| %>
        <li><%= answer.content %></li>
      <% end %>
    </ol>
  </li>
<% end %>
</ol>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back to Surveys', surveys_path %>